config/routes.rb
Rollup::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root :to => "pages#show", :slug => 'index'
  
  get ':slug' => 'pages#show', :as => :page_slug 

  resources :pages
  resources :stands do
    get ':slug' => 'stand_types#show', :as => :stand_type_slug
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, 
					:recoverable, :rememberable, :trackable, :validatable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :remember_me
	# attr_accessible :title, :body
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :slug, :position, :name, :content


  validates :slug, presence: true, uniqueness: true
  validates :name, presence: true

  acts_as_list
  
  extend FriendlyId
  friendly_id :slug

  default_scope order('position')
  scope :visible, -> { where(hidden: false) }
  scope :invisible, -> { where(hidden: true) }
  scope :without, (lambda do |field, values|
    raise "Unknown field :#{field} in Page model" unless field.to_s.in? attribute_names
    values = [values] unless values.is_a? Array
    where("#{field} NOT IN (?)", values)
  end)
end

app/models/stand.rb
class Stand < ActiveRecord::Base
  attr_accessible :slug, :hidden, :name, :position, :content, 
                  :stand_benefits_attributes, :stand_types_attributes,
                  :stand_options_attributes, :image

  validates :slug, presence: true, uniqueness: true
  validates :name, presence: true
  validates :content, presence: true
  validates :position, presence: true

  acts_as_list

  has_attached_file :image

  validates_attachment_presence :image
  validates_attachment_content_type :image,:content_type => ['image/jpeg', 'image/jpg', 'image/png']
  validates_attachment_size :image,:less_than => 5.megabytes

  has_many :stand_types, dependent: :destroy
  has_many :stand_benefits, :through => :stand_types, dependent: :destroy
  has_many :stand_options, :through => :stand_types, dependent: :destroy

  accepts_nested_attributes_for :stand_types, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :stand_benefits, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :stand_options, :allow_destroy => true, :reject_if => :all_blank

  extend FriendlyId
  friendly_id :slug

  default_scope order('position')
  scope :visible, -> { where(hidden: false) }
  scope :invisible, -> { where(hidden: true) }
end

app/models/stand_benefit.rb
class StandBenefit < ActiveRecord::Base
	attr_accessible :title, :content, :stand_type_id

	validates :title, presence: true
	validates :content, presence: true

	belongs_to :stand_type

	accepts_nested_attributes_for :stand_type, :allow_destroy => true, :reject_if => :all_blank

end

app/models/stand_option.rb
class StandOption < ActiveRecord::Base
	attr_accessible :stand_price, :print_price, :size, :stand_type_id

	validates :stand_price, presence: true
	validates :print_price, presence: true
	validates :size, presence: true

	belongs_to :stand_type

	accepts_nested_attributes_for :stand_type, :allow_destroy => true, :reject_if => :all_blank

end

app/models/stand_type.rb
class StandType < ActiveRecord::Base
  attr_accessible :stand_benefits_attributes, :stand_options_attributes, :slug, :hidden,
                  :name, :position, :content, :image, :stand_id, :complect_info

  validates :complect_info, presence: true
  validates :slug, presence: true, uniqueness: true
  validates :name, presence: true
  validates :position, presence: true

  has_attached_file :image

  acts_as_list

  validates_attachment_content_type :image,:content_type => ['image/jpeg', 'image/jpg', 'image/png']
  validates_attachment_size :image,:less_than => 5.megabytes

  belongs_to :stand
  has_many :stand_benefits, dependent: :destroy
  has_many :stand_options, dependent: :destroy

  accepts_nested_attributes_for :stand_benefits, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :stand_options, :allow_destroy => true, :reject_if => :all_blank
  accepts_nested_attributes_for :stand, :allow_destroy => true, :reject_if => :all_blank

  extend FriendlyId
  friendly_id :slug

  default_scope order('position')
  scope :visible, -> { where(hidden: false) }
  scope :invisible, -> { where(hidden: true) }
  scope :without, (lambda do |field, values|
    raise "Unknown field :#{field} in Page model" unless field.to_s.in? attribute_names
    values = [values] unless values.is_a? Array
    where("#{field} NOT IN (?)", values)
  end)
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    @page = Page.find_by_slug(params[:slug]) || Page.find(params[:slug])
    @stands = Stand.where("position<?", 5)
    render params[:slug] if controller_view_exists?(params[:slug])
  end

  private

  def view_exists?(view)
    File.exists? Rails.root.join("app", "views", view)
  end

  def controller_view_exists?(name)
    view_exists?("#{params[:controller]}/#{name}.html.erb")
  end
end

app/controllers/stand_types_controller.rb
class StandTypesController < ApplicationController
	def show
		@stands = StandType.find_by_slug(params[:slug]) || StandType.find(params[:slug])
		render params[:slug] if controller_view_exists?(params[:slug])
		@options = @stands.stand_options
	end

	def view_exists?(view)
		File.exists? Rails.root.join("app", "views", view)
	end

	def controller_view_exists?(name)
		view_exists?("#{params[:controller]}/#{name}.html.erb")
	end

end

app/controllers/stands_controller.rb
class StandsController < ApplicationController
	def show
		@stand = Stand.find(params[:id])
		render params[:id] if controller_view_exists?(params[:id])
	end

	def view_exists?(view)
		File.exists? Rails.root.join("app", "views", view)
	end

	def controller_view_exists?(name)
		view_exists?("#{params[:controller]}/#{name}.html.erb")
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stand_helper.rb
module StandHelper

	def menu_item_state(stand)
		slug = params[:slug]
		if stand.slug == slug || stand.stand_types.find{|p| p.slug == slug }
			'current'
		end
	end
end

app/helpers/stand_type_helper.rb
module StandTypeHelper

	def image_link(stand)
		return image_tag Stand.find(stand.stand_id).image if stand.image.url.match("missing.png")
		return image_tag stand.image
	end

	def content(stand)
		return Stand.find(stand.stand_id).content
		return stand.content
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title><%= yield(:title) %> | Roll Up 2500</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="wrapper">
		<div>
			<%= render 'shared/header' %>
		</div>
		<%= yield %>
		<div>
			<%= render 'shared/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</div>
</body>
</html>

app/views/pages/index.html.erb
<% provide(:title, @page.name) %>
<div class="wrapper">
	<div class="row-fluid content">
		<%= render @stands %>
	</div>
	<div class="main_content">
		<%= @page.content %>
	</div>
</div>

app/views/pages/show.html.erb
<% provide(:title, @page.name) %>
<div class="wrapper">
	<div class="row-fluid content">
		<%= raw @page.content %>
	</div>
</div>

app/views/shared/_footer.html.erb
<p>
	<%= Time.now.year %>
</p>

app/views/shared/_header.html.erb
<p>
	<%= link_to "Мобильные стенды", root_path %>
	<%= render 'shared/menu' %>
</p>

app/views/shared/_menu.html.erb
<nav class="header-menu">
	<ul>
		<% Stand.visible.each do |stand| %>
				<li class="menu_item <%= menu_item_state(stand)%>">
					<%= link_to content_tag(:span, stand.name), stand_path(stand) %>  
					<% StandType.visible.each do |st| %>
						<% if st.stand_id==stand.id %>
							<ul class="nested_links hidden">
								<%= link_to content_tag(:span, st.name), stand_stand_type_slug_path(stand.slug, st.slug) %>
							</ul>
						<% end %> 
					<% end  %>
				</li>
		<% end %>
	</ul>
</nav>

app/views/stand_benefits/_stand_benefit.html.erb
<p>
	<li>
		<%= stand_benefit.title %>
	</li>
	<ul>
		<%= stand_benefit.content %>
	</ul>
<p>

app/views/stand_options/_stand_option.html.erb
<tbody>
	<tr>
		<td><%= @stands.name %></td>
		<td><%= stand_option.size %></td>
		<td><%= stand_option.stand_price %></td>
		<td><%= stand_option.print_price %></td>
	</tr>
</tbody>

app/views/stand_types/show.html.erb
<% provide(:title, @stands.name) %>
<div class="wrapper">
	<div class="row-fluid content">
		<%= image_link(@stands) %>
		<div>
			<%= raw content(@stands) %>
		</div>
		<%= render @stands.stand_benefits %>
		<div>
			<% if @options.count>0 %>
				<table>
					<thead>
						<tr>
							<th>Наименование</th>
							<th>Размер полотна</th>
							<th>Цена конструкции</th>
							<th>Стоимость печати</th>
						</tr>
					</thead>
					<%= render @options %>
				</table>
				<%= @options[0].complect_info %>
			<% end %>
		</div>
	</div>
</div>

app/views/stands/_stand.html.erb
<div>
	<div class="block <%=if stand.position==1 then  "first" else if stand.position==4 then "last" end end %>">
		<div class="column">
			<div class="title">
				<%= link_to stand.name, stand_path(stand) %>
			</div>
			<div class="content">
				<%= stand.content %>
			</div>
			<div>
				<%= link_to "Заказать", page_slug_path("order"), class: "button" %>
				<%= image_tag stand.image, class: "thumb" %>
			</div>
		</div>
	</div>
</div>

app/views/stands/show.html.erb
<% provide(:title, @stand.name) %>
<div class="wrapper">
	<div class="row-fluid content">
		<%= raw @stand.content %>
	</div>
</div>